set(EXTERNAL_PROJECTS_PREFIX ${CMAKE_BINARY_DIR}/external-projects)
set(EXTERNAL_PROJECTS_INSTALL_PREFIX ${EXTERNAL_PROJECTS_PREFIX}/installed)

include(GNUInstallDirs)
include(ExternalProject)

# MUST be called before any add_executable() # https://stackoverflow.com/a/40554704/8766845
link_directories(${EXTERNAL_PROJECTS_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR})
include_directories($<BUILD_INTERFACE:${EXTERNAL_PROJECTS_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}>)

ExternalProject_Add(logfault
    PREFIX "${EXTERNAL_PROJECTS_PREFIX}"
    GIT_REPOSITORY "https://github.com/jgaa/logfault.git"
    GIT_TAG "master"
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${EXTERNAL_PROJECTS_INSTALL_PREFIX}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_GENERATOR='${CMAKE_GENERATOR}'
        -DCMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
)


ExternalProject_Add(mysqlpool
    PREFIX "${EXTERNAL_PROJECTS_PREFIX}"
    GIT_REPOSITORY "https://github.com/jgaa/mysqlpool-cpp.git"
    #GIT_REPOSITORY "/home/jgaa/src/mysqlpool-cpp"
    GIT_TAG "main"
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${EXTERNAL_PROJECTS_INSTALL_PREFIX}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_GENERATOR='${CMAKE_GENERATOR}'
        -DCMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
        -DDBOOST_ROOT=${BOOST_ROOT}
        -DMYSQLPOOL_LOGGER=logfault
        -DMYSQLPOOL_LOG_LEVEL_STR=trace
        -DMYSQLPOOL_DBUSER=NEXTAPP_DBUSER=NEXTAPP_DBUSER
        -DMYSQLPOOL_DBPASSW=NEXTAPP_DBPASSW
        -DMYSQLPOOL_DATABASE=NEXTAPP_DATABASE
        -DMYSQLPOOL_HOST=NEXTAPP_DBHOST
        -DMYSQLPOOL_PORT=NEXTAPP_DBPORT
        -DDEFAULT_MYSQLPOOL_DBUSER=nextapp
        -DDEFAULT_MYSQLPOOL_DATABASE=nextapp
        -DUSE_BOOST_VERSION='${USE_BOOST_VERSION}'
        -DMYSQLPOOL_WITH_TESTS=OFF
        -DLOGFAULT_ROOT='${EXTERNAL_PROJECTS_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}'
)

add_dependencies(mysqlpool logfault)

ExternalProject_Add(HowardHinnantDate
    PREFIX "${EXTERNAL_PROJECTS_PREFIX}"
    GIT_REPOSITORY "https://github.com/HowardHinnant/date.git"
    GIT_TAG "master"
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${EXTERNAL_PROJECTS_INSTALL_PREFIX}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_GENERATOR='${CMAKE_GENERATOR}'
        -DCMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
        -DBUILD_TZ_LIB=ON
        -DUSE_OS_TZDB=1
        -DHAS_REMOTE_API=0
        -DAUTO_DOWNLOAD=0
)
