name: Build macOS App

on:
  push:
    branches:
      - main
      
env:
  SRC_DIR:   ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/build
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_TRIPLET: arm64-osx-release
  VCPKG_INSTALL_OPTIONS: "--clean-after-build"
  VCPKG_MANIFEST_MODE: "ON"

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run macOS build script
        run: ./building/macos/build-nextapp.sh

      - name: Read NEXTAPP_VERSION from file
        shell: bash
        run: |
          ver=$(< "${{ env.BUILD_DIR }}/VERSION.txt")
          # export it for subsequent steps
          echo "NEXTAPP_VERSION=$ver" >> $GITHUB_ENV
          echo "✅ NEXTAPP_VERSION=$ver"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextapp-macos-arm64-dmg-${{ env.NEXTAPP_VERSION }}
          path: ${{ env.BUILD_DIR }}/*.dmg
          retention-days: 3
