name: Build and Push NextApp Docker Images

on:
  push:
    branches:
      - main
  release:
    types: [published]  # Run when a release is published

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Uses Ubuntu for Docker support

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT }}

      - name: Prepare build directory
        run: |
          mkdir build
          chmod 777 build
        shell: bash

      - name: Build and push nextappd image
        run: |
          chmod +x ./building/build-nextapp-image.sh  # Ensure script is executable
          BUILD_DIR=`pwd`/build REGISTRY=ghcr.io/jgaa ./building/build-nextapp-image.sh --scripted --strip --push
        shell: bash

      - name: Build and push signupd image
        run: |
          chmod +x ./building/build-signup-image.sh  # Ensure script is executable
          BUILD_DIR=`pwd`/build REGISTRY=ghcr.io/jgaa ./building/build-signup-image.sh --scripted --strip --push
        shell: bash