name: Build and Push NextApp Docker Images

on:
  push:
    branches:
      - main
  release:
    types: [published]  # Run when a release is published

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Uses Ubuntu for Docker support

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT }}

      - name: Prepare build directory
        run: |
          mkdir build
          chmod 777 build
          mkdir -p artifacts          
        shell: bash

      - name: Build and push nextappd image
        run: |
          chmod +x ./building/build-nextapp-image.sh  # Ensure script is executable
          export BUILD_DIR=`pwd`/build/nextapp
          export SYM_ARTIFACTS_DIR=`pwd`/artifacts
          REGISTRY=ghcr.io/jgaa ./building/build-nextapp-image.sh --scripted --strip --push
        shell: bash
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/*

      - name: Build and push signupd image
        run: |
          chmod +x ./building/build-signup-image.sh  # Ensure script is executable
          BUILD_DIR=`pwd`/build REGISTRY=ghcr.io/jgaa ./building/build-signup-image.sh --scripted --strip --push
        shell: bash
