name: Build macOS App

on:
  push:
    branches:
      #- main
      - macos-ga
      
permissions:
  contents: read

env:
  SRC_DIR:   ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/build
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_TRIPLET: arm64-osx-release
  VCPKG_INSTALL_OPTIONS: "--clean-after-build"
  VCPKG_MANIFEST_MODE: "ON"
  SIGN_ID: "Developer ID Application: The Last Viking LTD ood (G7GPB64J77)"

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.DEV_ID_P12 }} 
          p12-password:   ${{ secrets.DEV_ID_P12_PASS }}
            
      - name: Cache vcpkg directory
        uses: actions/cache@v4
        with:
          # Cache the entire vcpkg folder
          path: ${{ env.VCPKG_ROOT }}
          # Key on runner OS + triplet + hash of your vcpkg-all.json manifest
          key: vcpkg-${{ runner.os }}-${{ env.VCPKG_TRIPLET }}-${{ hashFiles('building/macos/build-configs/vcpkg-all.json') }}

      - name: Run macOS build script
        run: ./building/macos/build-nextapp.sh

      - name: Read NEXTAPP_VERSION from file
        shell: bash
        run: |
          ver=$(< "${{ env.BUILD_DIR }}/VERSION.txt")
          # export it for subsequent steps
          echo "NEXTAPP_VERSION=$ver" >> $GITHUB_ENV
          echo "✅ NEXTAPP_VERSION=$ver"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextapp-macos-arm64-dmg-${{ env.NEXTAPP_VERSION }}
          path: ${{ env.BUILD_DIR }}/*.dmg
          retention-days: 3
