name: Build NextApp Flatpak (Static Qt)

on:
  push:
    branches:
      - main
      - devel

permissions:
  contents: read
      
jobs:
  build:
    name: Build NextApp in Docker (Static Qt)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT }}

      - name: Run build script in Docker container
        run: |
          export BUILD_IMAGE=ghcr.io/jgaa/qt-static:latest
          cd building/static-qt
          bash build-nextapp.sh 1

      - name: Get NEXTAPP_VERSION 
        shell: bash
        run: |
          ver=$(grep -Po '(?<=set\(NEXTAPP_VERSION\s)[^)]+' CMakeLists.txt)
          # export it for subsequent steps
          echo "NEXTAPP_VERSION=$ver" >> $GITHUB_ENV
          echo "✅ NEXTAPP_VERSION=$ver"

      - name: Upload NextApp.flatpak artifact (valid for 3 days)
        uses: actions/upload-artifact@v4
        with:
          name: NextApp.flatpak-${{ env.NEXTAPP_VERSION }}
          path: building/static-qt/target/NextApp.flatpak
          retention-days: 3

